### PR TITLE
Add nodes, edges, inputs and queries for setting the final demand oil mix for households, buildings, industry and agriculture sectors

### PR DESCRIPTION
**Pull request by noracato**
Goes with quintel/etmodel#3776
Closes quintel/etmodel#3760

### Mix of oil types
In the households, buildings, industry and agriculture sectors the `final_demand_crude_oil` node now is a mixer that mixes 7 subtypes of final demand oil into `crude_oil`, before being distributed to other left-hand nodes. The demands of these subtypes are read directly from the energy balance:

- **kerosene** `kerosene_type_jet_fuel` + `other_kerosene`
- **bio-kerosene** 0.0 _this data is available, but not ready in the energy balance_
- **diesel** `gas/diesel_oil`
- **biodiesel** `biodiesels` 
- **lpg** `"liquefied_petroleum_gases_(lpg)" `
- **other oil** `"crude/ngl/feedstocks_(if_no_detail)" `+ `crude_oil` + `natural_gas_liquids` + `"additives/blending_components"` + `other_hydrocarbons` +` refinery_gas` + `ethane` + `motor_gasoline` + `aviation_gasoline` + `gasoline_type_jet_fuel` +` fuel_oil `+ `naphtha` + `"white_spirit_&_sbp"` + `lubricants` + `bitumen` + `paraffin_waxes` + `petroleum_coke` + `"non-specified_oil_product`
- **other bio-oil** `biogasoline` + `other_bio_fuels` + `non-specified primary biofuels and waste`

### Note about agriculture
One remark is the `agriculture_final_demand_crude_oil` node behaving differently (see a8870cf). This node only takes the carrier `crude_oil` as input, as opposed to the carriers fitting the oil subtypes.

The `de` dataset has 0 demand for any oil type in the agriculture sector, causing the mixer to fail if all subtypes were to be mixed. For this special case, @marliekeverweij and I decided to change the behaviour of the agriculture node. In the future, if the `de` dataset changes, we can change this back

### CODE REVIEW

**Comment by noracato** [comment]
This one's ready for review @redekok. I added the sparse graph queries for exporting from etlocal (see quintel/etlocal#328).

**Comment by redekok** [comment]
LGTM! 🎉  Some conflicts in the graph values for Heerhugowaard popped up in the meantime though..

**Review by redekok — CHANGES_REQUESTED** [review]
The conflicts in the graph values for Heerhugowaard should be solved before merging. 🤓

**Review by redekok — APPROVED** [review]
LGTM, ready to merge! 🚀

**Pull request merged**
