### PR TITLE
Rename NL2019 dataset to NL, NL to NL2015

### PR DESCRIPTION
**Pull request by antw**
* Curves that were shared between NL and NL2019 have been kept in the nl/curves directory, with symlinks placed in nl2015/curves.
* The other NL datasets (nl2016/nl2017/nl2018) still symlink data such as shares, energy balanced, etc, from NL2015.

### CODE REVIEW

**Comment by antw** [comment]
I've remade this PR with a new commit to fix conflicts caused by recent updates to NL2019.

**Comment by mabijkerk** [comment]
When I open a blank nl scenario on ETModel, the base year is 2019, as expected. The dataset name in ETEngine is nl2019, as expected. When I then try to change the dataset in ETEngine in the Edit scenario function to nl2015, I first have to run `rake decrypt` to fix Refinery errors. After running it again I get the following error:

```
No such file or directory @ rb_sysopen - /Users/{USER}/Projects/etsource/datasets/nl2015/curves/industry_chemicals_electricity.csv
```

**Comment by mabijkerk** [comment]
When I try to open a dataset that is linked to the nl2015 dataset, I get the same error as described above. For example for the dataset, Groningen: Zeeheldenbuurt, BU00140106_zeeheldenbuurt.

**Comment by antw** [comment]
Sorry, the nl2015 curves were accidentally linked using absolute paths that worked for me, but not for anyone else. It should now be fixed.

**Comment by kaskranenburgQ** [comment]
@mabijkerk Can we close this? 
 I think  a new effort must be made, since there are a lot of conflicts at the moment.

**Pull request closed without merging**
