### PR TITLE
Car input fix

### PR DESCRIPTION
**Pull request by ChaelKruip**
Fixes https://github.com/quintel/etsource/issues/1223

### CODE REVIEW

**Comment by antw** [comment]
@ChaelKruip Do you know why these inputs balance the share of gasoline automatically?

```ruby
UPDATE(LINK(transport_useful_demand_car_kms,transport_car_using_gasoline_mix), share,
  ->{SUM(NEG(SUM(V(EXCLUDE(INPUT_LINKS(V(transport_useful_demand_car_kms)),UPDATE_COLLECTION()), share))), 1)})
```

This is pretty non-standard (e.g. heating inputs [only set the share of the link](https://github.com/quintel/etsource/blob/cf29e6472830246907b99ef163c7f73ec391171e/inputs/demand/households/households_heating/households_space_heater_micro_chp_network_gas_share.ad#L1)); the user is expected to provide the entire group of inputs or permit the auto-balancer to make adjustments automatically. This balancing [predates "modern" ETSource+Atlas](https://github.com/quintel/etsource/blame/1ec83d5ee69814a5eb4b616bd5bd7ab07c8415ed/data/inputs/transport/transport_car/transport_car_using_compressed_natural_gas_share.ad) so it might be that we can remove it.

**Comment by ChaelKruip** [comment]
> @ChaelKruip Do you know why these inputs balance the share of gasoline automatically?

No :blushing:
We currently have about 200 inputs which use this type of 'balancing' inside the input-statement. If that can be removed I'd be happy to do that!

**Comment by antw** [comment]
> We currently have about 200 inputs which use this type of 'balancing' 

Right you are! I guess it's not as "non-standard" as I thought. Still, it's strange that this [is used in heating for buildings](https://github.com/quintel/etsource/blob/cf29e6472830246907b99ef163c7f73ec391171e/inputs/demand/buildings/buildings_heating/buildings_space_heater_electricity_share.ad) but not [heating for households](https://github.com/quintel/etsource/blob/cf29e6472830246907b99ef163c7f73ec391171e/inputs/demand/households/households_heating/households_space_heater_electricity_share.ad). I don't see any obvious difference in the graph: both have a useful demand node with input links from each technology. In fact, the network gas heater links are `flexible` which means they'll be automatically "balanced" anyway, even without the manual balancing in the input statements.

Would you mind if I experimented with this briefly before merging? It would be a small win if it turns out we can eliminate the manual balancing in the input statement.

**Comment by ChaelKruip** [comment]
> Would you mind if I experimented with this briefly before merging?

Not at all!

>  It would be a small win if it turns out we can eliminate the manual balancing in the input statement.

👍

**Comment by antw** [comment]
Superseded by #1237. Removing INPUT_VALUE helped fix #1236; thanks!

**Pull request closed without merging**
