### PR TITLE
Add baseload hydrogen plant

### PR DESCRIPTION
**Pull request by redekok**
Fixes https://github.com/quintel/etmodel/issues/3004:
- Add `energy_power_combined_cycle_hydrogen` node
- Add edges for `energy_power_combined_cycle_hydrogen`
- Add input for `energy_power_combined_cycle_hydrogen`
- Add queries for relevant charts and update electricity production query for the hydrogen network mekko chart

### CODE REVIEW

**Comment by redekok** [comment]
Depends on how quickly you (and @MartLubben) want to work with the new hydrogen plant (i.e., integrate it in the scenarios, etc.)? If it can wait until Monday, I think I would be in favor of stalling the merge until we get a response from Adriaan de Bakker.

**Comment by AlexanderWirtz** [comment]
We can wait a bit longer, but it is up to you to plan this.

**Comment by redekok** [comment]
In that case, I'll wait until Tuesday. If Adriaan has responded by that time, I will update the specs. If not, I'll just merge the PR and, if necessary, update the specs later.

**Comment by AlexanderWirtz** [comment]
I will leave it up to @ChaelKruip and @antw but if at all possible, it would be great if this could be cherry picked to Live at some point. No big rush, but @MartLubben and I would like to start working on Live at some point

**Comment by antw** [comment]
> I will leave it up to @ChaelKruip and @antw

The impact of cherry-picking this looks to be pretty low. I'm perfectly happy for us to do this.

We'd need to take:

**ETSource**
* quintel/etsource@5899d54

**ETEngine**
* quintel/etengine@461f11c

**ETModel**

* quintel/etmodel@7b89bb79

**Comment by redekok** [comment]
> **ETSource**
> - 5899d54
>
>**ETEngine**
>- quintel/etengine@461f11c
>
>**ETModel**
>- quintel/etmodel@7b89bb7

In addition to the commits above, I think we should cherry-pick these as well:

**ETSource**
- https://github.com/quintel/etsource/commit/0095f2ecb739d181da28dd7c1dbf0351b287cd08

**ETModel**
- https://github.com/quintel/etmodel/commit/3b2027c78ba8df6ef7ba5e212f90769684191ea5

Since @ChaelKruip is also fine with cherry-picking the baseload hydrogen plant to PRO, I will create a PR for this.

**Pull request merged**
