### PR TITLE
Biezen rename

### PR DESCRIPTION
**Pull request by BerendSmits**
As discussed in issue #1290, we removed the capital letter from the biezen dataset. @grdw can you run it once locally just to be sure?

### CODE REVIEW

**Comment by grdw** [comment]
@antw or @dennisschoenmakers could one of you check why Semaphore is failing? 👼

**Comment by antw** [comment]
@grdw Do you not have access to Semaphore? 😕 

```
Failures:

  1) Load profiles for DE_BIEZEN should have a industry_heat load profile
     Failure/Error: expect(dataset.load_profile_path(prof_name)).to be_file
       expected file? to return true, got false
     # ./spec/load_profiles_spec.rb:17:in `block (5 levels) in <top (required)>'
```

screen shot 2017-08-03 at 17 44 42

I had to add two new commits to work around this: the first to delete the old aliased CSV file (in `de_Biezen`), and a second to add it back in (in `de_biezen`). I'm not sure why it affected only this file; it's new, but not any different to the other aliased CSVs.

**Comment by grdw** [comment]
> @grdw Do you not have access to Semaphore? 😕

Well, not to all projects somehow 🤔 

screen shot 2017-08-04 at 09 15 07

This is what I have.

**Comment by antw** [comment]
> Well, not to all projects somehow 🤔

I don't seem to have the ability to add you to any projects, unfortunately. @dennisschoenmakers: When you have time, could you arrange this please? @grdw is missing access to etsource, etflex, and mechanical_turk.

**Pull request merged**
