### PR TITLE
Heat mekko

### PR DESCRIPTION
**Pull request by ChaelKruip**
Queries for heat mekko:
energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_

The SQL statements to include this chart:
```
INSERT INTO `output_element_series` (`id`, `output_element_id`, `label`, `color`, `order_by`, `group`, `created_at`, `updated_at`, `show_at_first`, `is_target_line`, `target_line_position`, `gquery`)
VALUES
    (NULL, 174, 'agriculture_locally_available_steam_hot_water_in_heat_network_mekko', '#DFFBE5', 4, 'demand', NOW(), NOW(), NULL, 1, NULL, 'agriculture_locally_available_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'agriculture_unused_local_production_steam_hot_water_in_heat_network_mekko', '#DFFBE5', 2, 'demand', NOW(), NOW(), NULL, 1, NULL, 'agriculture_unused_local_production_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'energy_heat_network_loss_in_heat_network_mekko', '#8B0000', 3, 'demand', NOW(), NOW(), NULL, 1, NULL, 'energy_heat_network_loss_in_heat_network_mekko'),
    (NULL, 174, 'energy_heat_network_unused_steam_hot_water_in_heat_network_mekko', '#CC0000', 1, 'demand', NOW(), NOW(), NULL, 1, NULL, 'energy_heat_network_unused_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'households_heat_network_connection_steam_hot_water_in_heat_network_mekko', '#4E60D1', 5, 'demand', NOW(), NOW(), NULL, 1, NULL, 'households_heat_network_connection_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'industry_locally_available_steam_hot_water_in_heat_network_mekko', '#00A7B4', 6, 'demand', NOW(), NOW(), NULL, 1, NULL, 'industry_locally_available_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'other_final_demand_steam_hot_water_in_heat_network_mekko', '#8643A9', 7, 'demand', NOW(), NOW(), NULL, 1, NULL, 'other_final_demand_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'buildings_heat_network_connection_steam_hot_water_in_heat_network_mekko', '#394C19', 8, 'demand', NOW(), NOW(), NULL, 1, NULL, 'buildings_heat_network_connection_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'industry_unused_local_production_steam_hot_water_in_heat_network_mekko', '#00A7B4', 15, 'supply', NOW(), NOW(), NULL, 1, NULL, 'industry_unused_local_production_steam_hot_water_in_heat_network_mekko'),
    (NULL, 174, 'energy_chp_combined_cycle_network_gas_in_heat_network_mekko', '#CCCCCC', 2, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_chp_combined_cycle_network_gas_in_heat_network_mekko'),
    (NULL, 174, 'energy_chp_supercritical_waste_mix_in_heat_network_mekko', '#394C19', 3, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_chp_supercritical_waste_mix_in_heat_network_mekko'),
    (NULL, 174, 'energy_chp_ultra_supercritical_coal_in_heat_network_mekko', '#333333', 4, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_coal_and_lignite_chps_in_heat_network_mekko'),
    (NULL, 174, 'energy_heat_network_backup_heater_network_gas_in_heat_network_mekko', '#CC0000', 1, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_heat_network_backup_heater_network_gas_in_heat_network_mekko'),
    (NULL, 174, 'energy_heater_for_heat_network_coal_in_heat_network_mekko', '#333333', 7, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_coal_and_lignite_heaters_in_heat_network_mekko'),
    (NULL, 174, 'energy_heater_for_heat_network_crude_oil_in_heat_network_mekko', '#854321', 8, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_heater_for_heat_network_crude_oil_in_heat_network_mekko'),
    (NULL, 174, 'energy_heater_for_heat_network_geothermal_in_heat_network_mekko', '#BA7D40', 9, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_heater_for_heat_network_geothermal_in_heat_network_mekko'),
    (NULL, 174, 'energy_heater_for_heat_network_network_gas_in_heat_network_mekko', '#666666', 11, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_heater_for_heat_network_network_gas_in_heat_network_mekko'),
    (NULL, 174, 'energy_heater_for_heat_network_waste_mix_in_heat_network_mekko', '#394C19', 12, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_heater_for_heat_network_waste_mix_in_heat_network_mekko'),
    (NULL, 174, 'energy_heater_for_heat_network_wood_pellets_in_heat_network_mekko', '#5D7929', 13, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_heater_for_heat_network_wood_pellets_in_heat_network_mekko'),
    (NULL, 174, 'energy_power_supercritical_waste_mix_in_heat_network_mekko', '#394C19', 14, 'supply', NOW(), NOW(), NULL, 1, NULL, 'energy_power_supercritical_waste_mix_in_heat_network_mekko');
```

### CODE REVIEW

**Comment by jorisberkhout** [comment]
Looks very good, @ChaelKruip ! One remark with the SQL statement, should we not also add a new output element (#174)? I couldn't find that in the SQL statement.

I will merge this pull request and import it in Beta ETEngine.

**Comment by ChaelKruip** [comment]
> should we not also add a new output element (#174)?

True! 👍

**Comment by AlexanderWirtz** [comment]
Should we perhaps group all Central fossil heaters (except for the backup and the Central waste heater), just to get rid of some entries? These are not often used in scenarios.

**Comment by AlexanderWirtz** [comment]
I cannot find this output element in the database (174), so I guess we should add it.

**Pull request merged**
