### PR TITLE
Added compressed_network_gas to FD MECE network gas for transport query

### LINKED ISSUE #1110: compressed network gas should be included in final demand queries
Currently, it does not show up in the Mekko:
energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_

This query does not contain the carrier:
[https://github.com/quintel/etsource/blob/master/gqueries/general/final_demand/mece/final_demand_of_natural_gas_and_derivatives_in_transport.gql](https://github.com/quintel/etsource/blob/master/gqueries/general/final_demand/mece/final_demand_of_natural_gas_and_derivatives_in_transport.gql)

### PR DESCRIPTION
**Pull request by RobTerwel**
Closes #1110.

### CODE REVIEW

**Comment by ChaelKruip** [comment]
@RobTerwel do you think there might be other place where this carrier needs to be added now that we are at it? 😄

**Comment by RobTerwel** [comment]
> @RobTerwel do you think there might be other place where this carrier needs to be added now that we are at it? 😄

I'll go over it again; the carrier already existed before the introduction of the compressor, but I agree a little searching wouldn't hurt!

**Comment by RobTerwel** [comment]
Good point you raised there, apparently it has never been part of many queries! I will add it right away. 🎅

**Comment by RobTerwel** [comment]
This should be it. 😄

**Pull request merged**
