### PR TITLE
Hydrogen improvements kerosene

### PR DESCRIPTION
**Pull request by kaskranenburgQ**
This PR adds flexible synthetic kerosine to the model. Goes together with [ETModel #4253](https://github.com/quintel/etmodel/pull/4253)  
This flexibility option is based on the electricity price and is an addition to the power, hydrogen & Co2 modelling.

The components that have been added are:
- Split up of the old synthetic kerosene nodes into baseload (in PJ) and dispatchable (in MWe-input) nodes.
- Addition of a WTP component for the dispatchable kerosene production.
- Addition of the flexible component to the relevant flexible power graphs.
- Refinement of the graph queries where needed.

### CODE REVIEW

**Comment by kaskranenburgQ** [comment]
Just realised that now the slide text for the willingness to pay slider is called "Conversion to kerosene for industry" 
Screenshot 2024-05-01 at 13 51 31
However, is this kerosene used in the industry? Should it be renamed to Conversion to kerosene?

**Comment by mabijkerk** [comment]
Well-spotted, @kaskranenburgQ I'll change it!

**Comment by mabijkerk** [comment]
Even when I set the WTP to maximum, the peak capacity (3rd column), never reaches the installed capacity (2nd column) in the table "Flexible electricity demand technologies". Why is this the case?

Screenshot 2024-05-01 at 16 28 32

**Comment by kaskranenburgQ** [comment]
> Follow-up: it is because the query `V(energy_production_synthetic_kerosene_dispatchable, "number_of_units * input_capacity")`, but the `input_capacity` is split between 55% electricity and 45% hydrogen.

Great spot @mabijkerk, I tried fixing this by changing capacity_of_energy_production_synthetic_kerosene_dispatchable
to:

`    UPDATE(
        V(energy_production_synthetic_kerosene_dispatchable),
        number_of_units,
        DIVIDE(
            USER_INPUT(),
            DIVIDE(
            V(energy_production_synthetic_kerosene_dispatchable,input_capacity),    
            V(energy_production_synthetic_kerosene_dispatchable,input.electricity)   
        )`

This does not seem to work since 'input.electricity' can't be found.

**Review by mabijkerk — APPROVED** [review]
Nice work!

**Pull request merged**
