### PR TITLE
Addition of appliances graph

### PR DESCRIPTION
**Pull request by kaskranenburgQ**
Closing issue [#4120](https://github.com/quintel/etmodel/issues/4120) 
Goes together with PR [4178](https://github.com/quintel/etmodel/pull/4178) of ETModel

### CODE REVIEW

**Comment by kaskranenburgQ** [comment]
I rebased the PR, testing should work again.

**Comment by mabijkerk** [comment]
@kaskranenburgQ thanks for bringing this up to date. Based on the discussions we have had about gqueries in the meantime, I'd rather have the chart queries be based on the final demand queries in the general folder. See [appliances_buildings](https://github.com/quintel/etsource/tree/master/gqueries/general/final_demand/buildings/appliances_buildings).

**Comment by kndehaan** [comment]
Is this PR still up-to-date and can this be merged and closed in the near future? Or is the better alternative here to close the PR and rewrite to an issue?

**Comment by kaskranenburgQ** [comment]
Rebased the branches and took on your feedback @mabijkerk.
The queries are now based on the final demand queries in the appliances folder. 
I renamed the various series labels in the chart to the relevant carrier group, we could also chose to revert this. Please see the table below for the old and new labels:


| Old label (based on one carrier)  | New label (based on final demand querie group |
| ------------- | ------------- |
| Coal   | Coal and coal products* |
| Wood pellets  | Biomass products  |
| Network gas  | Network gas |
| Electricity | Electricity |
| Oil   | Oil and derivatives* |

*At the moment, the Dutch label is Kool en koolproducten, and Olie en Olieproducten

Please let me know what you think!

**Review by mabijkerk — APPROVED** [review]

**Pull request merged**
