### PR TITLE
Adjusting the base_cop and cop_per_degree to match hybrid heatpumps

### LINKED ISSUE #2881: SCOP of air heatpump & hybrid heatpump differ
The base_cop & cop_per_degree were adjusted for hybrid heatpumps but not for air heatpumps.
Currently their efficiency differs even though we are talking about the same technique and same datasource (https://refman.energytransitionmodel.com/publications/2063).
The base_cop & cop_per_degree for the air heatpump should be changed accordingly as these numbers have been correctly updated for hybrid heatpumps.

### PR DESCRIPTION
**Pull request by Charlottevm**
closes #2881

### CODE REVIEW

**Review by mabijkerk — CHANGES_REQUESTED** [review]
LGTM!

Changing the COP does have a significant impact on electricity demand for space heating in scenarios where the air-water heat pump is installed. We should therefore write a migration that compensates for this efficiency drop in existing scenarios.

- [ ] Write migration to compensate for efficiency drop in existing scenarios with air heat pumps

Then we should still hold on with merging the PR, as the II3050v2 have just been published and we should aim for result and input stability.

**Comment by kaskranenburgQ** [comment]
Is it time to merge this?

**Comment by mabijkerk** [comment]
This goes with https://github.com/quintel/etdataset/pull/967. However, the the to do listed above is still relevant. If we want to do this, we first have to write a migration that mitigates the effect of the efficiency change. I will put it on the Modeller sprint.

**Comment by mabijkerk** [comment]
Picked up in https://github.com/quintel/etsource/pull/3091

**Pull request closed without merging**
