### PR TITLE
Network gas compressor for transport

### PR DESCRIPTION
**Pull request by RobTerwel**
This PR replaces the old `transport_compressor_network_gas` with `energy_compressor_network_gas` and renames some nodes, edges and shares accordingly.

### CODE REVIEW

**Comment by jorisberkhout** [comment]
I fully agree with the changes in this PR.

There is a merge conflict in the encrypted energy balances. It doesn't matter which of the two conflicting copies is checked out. Would you be so kind to have a look at this, @ChaelKruip . Otherwise it will be waiting until I'm back from holidays.

I merged the ETEngine part of this in https://github.com/quintel/etengine/pull/827. Once ETSource is merged and tested, the ETDataset PR can be merged as well.

**Comment by ChaelKruip** [comment]
@RobTerwel can you give more background as to why these changes are made? Maybe link to an issue?

**Comment by ChaelKruip** [comment]
Also, do you know why there are merge-conflicts in this branch?

**Comment by RobTerwel** [comment]
> @RobTerwel can you give more background as to why these changes are made? Maybe link to an issue?

There is no issue for this but this was discussed with @jorisberkhout and John. The reason is the following: the current `transport_road_compressor_network_gas` does not have any costs or efficiency attributes associated with it, hence you'd be driving on plain, uncompressed and very cheap network gas. Secondly, the converter should appear *before* the `transport_final_demand.(..)` converter since the transport nodes are FD EB-initialised and we otherwise subtract losses that occured *before* utilization if this compressor is put after the FD converter.

> Also, do you know why there are merge-conflicts in this branch?

Yes, @AlexanderWirtz and I both included the `energy_balance.gpg` files in parallel ETSource PRs and his got merged first. It doesn't matter which one you pick, as @jorisberkhout also explained before:

> There is a merge conflict in the encrypted energy balances. It doesn't matter which of the two conflicting copies is checked out.

**Comment by ChaelKruip** [comment]
Thanks for clarifying!

> as @jorisberkhout also explained before:

I overlooked that comment :smile:

**Comment by RobTerwel** [comment]
> Thanks for clarifying!

as @jorisberkhout also explained before:
I overlooked that comment :smile:

No worries! :smile:

**Pull request merged**
