### PR TITLE
Changed input.electricity fractions for ground source heat pumps in

### PR DESCRIPTION
**Pull request by AlexanderWirtz**
households and buildings. Documented in issue: https://github.com/quintel/etdataset/issues/652 . Fixes that issue.

### CODE REVIEW

**Comment by jorisberkhout** [comment]
I like the changes, @AlexanderWirtz !

We would, however, have to re-run all analyses for all datasets to make use of these new efficiencies. I will do that after https://github.com/quintel/etdataset/pull/650 is reviewed and merged and @RobTerwel has updated the transport analysis to export the hydrogen related shares. This should all be resolved well before the February deploy, so I added that milestone to this PR.

**Comment by AlexanderWirtz** [comment]
Agree @jorisberkhout

**Comment by jorisberkhout** [comment]
The required changes to the datasets on ETDataset and ETSource are part of https://github.com/quintel/etdataset/pull/659 and https://github.com/quintel/etsource/pull/1030 respectively. @RobTerwel has merged these pull requests and imported the changes to Beta ETEngine.

**Comment by MartLubben** [comment]
@jorisberkhout Which part of the COP of cooling is still an issue? If nothing, please close [this issue](https://github.com/quintel/etmodel/issues/1440).

**Pull request merged**
