### PR TITLE
No more max values

### PR DESCRIPTION
**Pull request by ChaelKruip**
Removes from the inputs:
* max_value
* start_value

The main thing to worry about is if there are slider caps (`max_value_gql`) that are smaller than the previous cap and therefore could change the slider settings of existing scenario's. 

I don't worry very much though because `max_value_gql` was leading in the first place and there are just a few inputs for which there was no `max_value_gql` and I checked that their new max is higher than previously set by the `max_value`. Still, it might be worth a bit of (automated?) testing.

Fixes https://github.com/quintel/etsource/issues/1213

### CODE REVIEW

**Comment by antw** [comment]
@ChaelKruip I pushed a small change; apparently ETE won't let you simply specify a number as a `_gql` attribute, but needs to be told which period to use:

* No: `- max_value_gql = 25000`
* Yes: `- max_value_gql = present:25000`

That seems an unnecessary requirement when the value is numeric, but for the sake of simplicity I fixed the three offending inputs and we can look to change ETE later.

Here are the changes from old to new:

* number_of_energy_chp_supercritical_waste_mix_present
  * max 21.325 → 426.497
* number_of_energy_flexibility_p2g_electricity
  * max 100000.0 → 31140.266
* number_of_industry_flexibility_p2g_electricity
  * max 100000.0 → 12436.644
* number_of_energy_chp_supercritical_waste_mix
  * max 21.325 → 426.497
* number_of_energy_heat_network_backup_heater_network_gas
  * max 1000.0 → 286.765
* number_of_energy_power_hydro_mountain
  * max 44.913 → 45.158
* policy_area_green_gas
  * max 5000.0 → 55427.1

Some of the changes are quite large, but if they seem right to you we can merge it.

**Comment by ChaelKruip** [comment]
> Some of the changes are quite large, but if they seem right to you we can merge it.

I think these changes are quite fine. 

@jorisberkhout @AlexanderWirtz do you agree? The maximum number of P2G units is now based on the assumption that you can build enough P2G to convert the total electricity production in the present year, twice.

**Comment by jorisberkhout** [comment]
I think the new max value for the P2G sliders are to tight. Although the exact value is arbitrary, I would suggest to keep them close to what they are at the moment (`100,000`). I have changed the `max_value_gql` for both sliders by increasing the factor `2` by which the total electricity production is multiplied to `6` for `energy_p2g` and `16` for `industry_p2g`. I have pushed these changes to this PR.

**Comment by ChaelKruip** [comment]
@antw can you merge this?

**Pull request merged**
