### PR TITLE
Profile updates for EVs

### PR DESCRIPTION
**Pull request by kaskranenburgQ**
This PR changes the profiles for electric vehicles.

- It changes the mapping of the profiles:

    '- electric_vehicle_profile_1: Charging in public
    '- electric_vehicle_profile_2 : Charging at home
    '- electric_vehicle_profile_3 : Fast charging
    '- electric_vehicle_profile_4 : Charging at work
    '- electric_vehicle_profile_5 Custom profile

It updates the profiles electric_vehicle_profile_1,  electric_vehicle_profile_2, electric_vehicle_profile_4 to ev profiles generated by Elaad. electric_vehicle_profile_5 is converted to a flat profile that can be overwritten by the users. 

Lastly, the standard settings in all datasets have been updated to the following settings:

electric_vehicle_profile_1_share': 0.24
 electric_vehicle_profile_2_share': '0.56'
electric_vehicle_profile_3_share': '0.08'
electric_vehicle_profile_4_share': '0.12'
electric_vehicle_profile_5_share': '0.0'

Goes together with:
- ETModel [4320](https://github.com/quintel/etmodel/pull/4320) 
- ETEngine [1453](https://github.com/quintel/etengine/pull/1453)

### CODE REVIEW

**Comment by mabijkerk** [comment]
@kaskranenburgQ in the end, what curve did you decide to assign to profile 5?

**Comment by mabijkerk** [comment]
What I noticed from this PR is that Ameland has its own curve set. Diving into Github shows that this was done in https://github.com/quintel/etsource/commit/9891b7c5ea3380377eea189f1b9dc0992cb199af to correct for seasonal tourist variation.

@DorinevanderVlies you have applied these changes. Are you okay with changes to Ameland being made? Most curves already seem to have been overwritten, for example in https://github.com/quintel/etsource/commit/01ded54e425d7efedd3df808eabc1fe21bd3f92b.

**Review by kndehaan — APPROVED** [review]
LGTM, no comments

**Comment by mabijkerk** [comment]
@kaskranenburgQ I think `dk`, `de` and `eu` should also be assigned the new curves. Additionally, for `UKNI01_northern_ireland`,  `electric_vehicle_profile_4` does not seem to be updated. Is that intentional?

**Comment by DorinevanderVlies** [comment]
> @DorinevanderVlies you have applied these changes. Are you okay with changes to Ameland being made? Most curves already seem to have been overwritten, for example in https://github.com/quintel/etsource/commit/01ded54e425d7efedd3df808eabc1fe21bd3f92b.

It's ok to overwrite the EV curves for Ameland!

**Review by mabijkerk — CHANGES_REQUESTED** [review]
- [ ] Check electric profile curve 4 for Northern Ireland
- [ ] Check electric profile curves for eu, dk and de
- [ ] Determine whether or not to update electric profile curve 5 from flat to a more representative base curve

**Comment by kaskranenburgQ** [comment]
@mabijkerk 

> [ ]  Determine whether or not to update electric profile curve 5 from flat to a more representative base curve
 I discussed this with @jorisberkhout earlier, we concluded that it would be more clear to initally show a flat curve at the custom curve.

**Pull request merged**
