### PR TITLE
Construction wood products bug

### PR DESCRIPTION
**Pull request by BerendSmits**
As referenced in issue https://github.com/quintel/etsource/issues/1359, the inputs and initializer input for wood_products actually updated the demand for construction. Construction is now replaced with wood_products)

### CODE REVIEW

**Comment by grdw** [comment]
You can also remove (I'm guessing):

- https://github.com/quintel/etsource/blob/master/inputs/demand/industry/industry_useful_demand_for_other_wood_products_efficiency.ad
- https://github.com/quintel/etsource/blob/master/inputs/demand/industry/industry_useful_demand_for_other_wood_products.ad
- https://github.com/quintel/etsource/blob/master/inputs/demand/industry/industry_useful_demand_for_other_construction_efficiency.ad

I guess, stating that they aren't actually used in the front-end of ETModel.

**Comment by BerendSmits** [comment]
> You can also remove (I'm guessing):

Yes I guess you are right, as far as I can see they are not used in any scenario's either. But as I do not know why they were created in the first place, I'm hesitant to just throw them away..

**Comment by grdw** [comment]
> But as I do not know why they were created in the first place, I'm hesitant to just throw them away..

I do not know either. I'll check if they are indeed never ever used, if that's the case, you have my blessing to throw them away. If somehow, somebody actually really really needs them - he/she can do a `git revert` anyway.

**Comment by grdw** [comment]
They aren't used in the `input_elements` table in ETModel. They aren't in any presets as far as I can see. Am I missing anyplace where these inputs *could* be used? @antw

**Comment by antw** [comment]
> Am I missing anyplace where these inputs could be used?

A different application perhaps, but I suspect those inputs were added too recently for that to be the case.

**Comment by BerendSmits** [comment]
>A different application perhaps, but I suspect those inputs were added too recently for that to be the case.

In that case, shall I remove them @grdw ?

**Comment by grdw** [comment]
> In that case, shall I remove them @grdw ?

**Comment by BerendSmits** [comment]
Same goes for: 

```
industry_useful_demand_for_other_machinery.ad
industry_useful_demand_for_other_machinery_efficiency.ad
industry_useful_demand_for_other_minerals.ad
industry_useful_demand_for_other_minerals_efficiency.ad
industry_useful_demand_for_other_mining.ad
industry_useful_demand_for_other_mining_efficiency.ad
industry_useful_demand_for_other_non_specified.ad
industry_useful_demand_for_other_non_specified_efficiency.ad
industry_useful_demand_for_other_textile.ad
industry_useful_demand_for_other_textile_efficiency.ad
industry_useful_demand_for_other_transport_equipment.ad
industry_useful_demand_for_other_transport_equipment_efficiency.ad
```

Right?

**Comment by grdw** [comment]
> Right?

Yep, throw it away please.

**Comment by BerendSmits** [comment]
> Yep, throw it away please.

Gone

**Pull request merged**
