### PR TITLE
Remove central producer class

### PR DESCRIPTION
**Pull request by marliekeverweij**
This PR merges the removal of the central producers class with the `nl2019` branch. The nl2019-update will contain regional specific efficiencies for power and heat plants and these efficiencies have been added to the central_producers.csv within each dataset.

### CODE REVIEW

**Comment by antw** [comment]
The tests are failing as the CSVs have a column "heat_output_conversion" instead of "steam_hot_water_output_conversion".

@marliekeverweij Is this easily fixable?

**Comment by marliekeverweij** [comment]
😓 

Done!

**Comment by antw** [comment]
Thanks! Two comments:

- The Belgian dataset (and its derived datasets) doesn't seem to be very happy: something to do with natural gas, but it's not immediately obvious why. If you don't know why either, I can try to figure it out early next week.

    ```
     Refinery::IncalculableGraphError:
       Insufficient data to calculate 18 items: 
     
         * EdgeDemand for #<Refinery::Edge :energy_import_natural_gas -:natural_gas-➤ :energy_treatment_natural_gas (type=flexible)>
         * NodeDemand for #<Refinery::Node key=:energy_import_natural_gas>
         * EdgeDemand for #<Refinery::Edge :energy_heat_unused_steam_hot_water -:steam_hot_water-➤ :energy_heat_dumped_steam_hot_water (type=flexible)>
         * NodeDemand for #<Refinery::Node key=:energy_heat_unused_steam_hot_water>
         * NodeDemand for #<Refinery::Node key=:energy_heat_dumped_steam_hot_water>
         * EdgeDemand for #<Refinery::Edge :energy_treatment_natural_gas -:natural_gas-➤ :energy_national_gas_network_natural_gas (type=)>
         * EdgeDemand for #<Refinery::Edge :energy_treatment_natural_gas -:natural_gas-➤ :energy_export_network_gas (type=overflow)>
         * NodeDemand for #<Refinery::Node key=:energy_treatment_natural_gas>
         * NodeDemand for #<Refinery::Node key=:energy_export_network_gas>
         * EdgeDemand for #<Refinery::Edge :energy_heat_burner_waste_mix -:steam_hot_water-➤ :energy_transmission_steam_hot_water (type=flexible)>
         * EdgeDemand for #<Refinery::Edge :energy_national_gas_network_natural_gas -:network_gas-➤ :energy_heat_backup_burner_network_gas (type=)>
         * NodeDemand for #<Refinery::Node key=:energy_national_gas_network_natural_gas>
         * EdgeDemand for #<Refinery::Edge :energy_heat_backup_burner_network_gas -:steam_hot_water-➤ :energy_production_aggregator_steam_hot_water (type=flexible)>
         * NodeDemand for #<Refinery::Node key=:energy_heat_backup_burner_network_gas>
         * EdgeDemand for #<Refinery::Edge :energy_transmission_steam_hot_water -:steam_hot_water-➤ :energy_production_aggregator_steam_hot_water (type=flexible)>
         * NodeDemand for #<Refinery::Node key=:energy_transmission_steam_hot_water>
         * EdgeDemand for #<Refinery::Edge :energy_production_aggregator_steam_hot_water -:steam_hot_water-➤ :energy_heat_unused_steam_hot_water (type=overflow)>
         * NodeDemand for #<Refinery::Node key=:energy_production_aggregator_steam_hot_water>
    ```

- There are rows in the CSVs where a conversion is set to 0, but the node doesn't have that carrier. For example, "energy_heat_burner_wood_pellets" has an `electricity_output_conversion` of 0, but in fact doesn't have an electricity output.

  Would the tooling / workflow generating these CSVs allow these cells to be blank instead of 0? I know it's a _small_ thing, but I feel it makes the CSVs easier to understand when such invalid values are omitted entirely.

**Comment by marliekeverweij** [comment]
Thanks for your feedback. I think I found the issue with the Belgian dataset: two efficiencies were mixed up.

> Would the tooling / workflow generating these CSVs allow these cells to be blank instead of 0? I know it's a small thing, but I feel it makes the CSVs easier to understand when such invalid values are omitted entirely.

Yes this is possible. We will adjust this in the ETDataset analyses!

**Pull request merged**
