### PR TITLE
Investment table

### PR DESCRIPTION
**Pull request by ChaelKruip**
This improves the investment table to correct for double counting.

Fixes https://github.com/quintel/etmodel/issues/1926

Fixes https://github.com/quintel/etmodel/issues/1927

Also see https://github.com/quintel/etmodel/pull/1992

### CODE REVIEW

**Comment by jorisberkhout** [comment]
I looked into the changes in this pull request and have a few questions / comments:

#### General

- I like the new 'rules' on the investment costs of heat pumps in households. For ground heat pumps in households they work fine (i.e. the table displays the highest required investment costs for heat pumps in space heating or hot water)
- The investment costs of heat pumps in buildings are displayed correctly as well
- The investment costs of air heat pumps in households, however, do not respond to the settings of either `Heat pump (air)` sliders
- One comment about the new 'rules' for the investment costs of heat pumps. You can now make your scenario unrealistically cheap by building a few heat pumps (ground or air) for space heating or hot water followed by supplying *all* cooling with these heat pumps as the latter will have no costs then. I am not saying this is an issue, but it is something to be aware of @ChaelKruip and @AlexanderWirtz .

> @AlexanderWirtz what about electric vehicles? They used to add no investment costs but now they will right?

- I found this comment in https://github.com/quintel/etmodel/issues/1926, but do not see the investments costs for EV in the table. I assume that you have chosen not to include these. Is this correct, @ChaelKruip ?

#### Layout

While reviewing the table, I also spotted some layout issues

- The layout of some rows is wrong. Specifically:
  - Under `Buildings` the rows `Coal-fired heater` and `Oil-fired heater`
  - Under `Buildings` the rows `Electric heater` and `Gas-fired heater`
  - Under `Households` the rows `Heat pump (air)` and `Hybrid heat pump`
- The `Agriculture` subheader is not consistent with the other subheaders (e.g. `Buildings`)
- I personally don't like the layout of the last three columns. Their headers say `Investment (BLN. EURO)` *and* each row says `€`. I would suggest to remove the `€` sign from each cell in the table.

**Comment by jorisberkhout** [comment]
After discussion with @ChaelKruip , we realised that their is two rows displaying the `Heat pump (air)` for `Households`.

**Comment by ChaelKruip** [comment]
> The investment costs of air heat pumps in households, however, do not respond to the settings of either Heat pump (air) sliders

The old 'cooling' queries were still included. I pushed a fix.

**Comment by ChaelKruip** [comment]
> The total costs displayed at the bottom of the table are not the same as the sum of the costs in all rows.

Pushed a fix for this that removes the doubling. Also take note of https://github.com/quintel/etmodel/issues/1994

**Comment by ChaelKruip** [comment]
> I assume that you have chosen not to include these. Is this correct, @ChaelKruip ?

Yes.

**Comment by ChaelKruip** [comment]
> The Agriculture subheader is not consistent with the other subheaders (e.g. Buildings)

> The layout of some rows is wrong. 

Pushed fixes for these.

**Comment by jorisberkhout** [comment]
Very nice, @ChaelKruip ! I will merge, import and deploy this.

**Pull request merged**
