### PR TITLE
Add hydrogen powered trains (freight and passenger)

### LINKED ISSUE #2487: Add input statements and nodes for hydrogen-powered passenger and freight trains
Names for input statements / nodes:
- transport_freight_train_using_hydrogen_share
- transport_passenger_train_using_hydrogen_share

https://github.com/quintel/etmodel/issues/3761

Research is done, see: https://github.com/quintel/etdataset/commit/d0640aa810c0131528fbe2ecc3c6ab6303d0e404

### PR DESCRIPTION
**Pull request by noracato**
Add nodes, edges and inputs for hydrogen powered trains!

As these are not in any datasets (present values), the share of hydrogen that flows from the `transport_final_demand_hydrogen` node to the rail section is hard-set to 0.0. In the rail section itself, 1.0 flows to the freight and 0.0 to passenger trains. These are hardcoded in the edges as well, as these shares do not matter (no hydrogen flows through them without touching an input).

---

Closes #2487 
Goes with quintel/etmodel#3789

### CODE REVIEW

**Comment by redekok** [comment]
The modelling LGTM! While testing I noticed that hydrogen powered passenger trains are much more efficient than electricity powered passenger trains, as opposed to freight trains where both efficiencies are equal. @MartLubben, is this indeed the case? (I'm asking you since you updated the node source analyses, didn't you?)

**Comment by MartLubben** [comment]
Interesting. I will take a look at this.

**Comment by MartLubben** [comment]
Is were indeed mistakes in the Excel, for both passenger and freigth trains, see fix. 
Linked to this Etdataset pull request: https://github.com/quintel/etdataset/pull/888

**Review by redekok — APPROVED** [review]
LGTM!

**Pull request merged**
