### PR TITLE
Nl2019

### PR DESCRIPTION
**Pull request by MartLubben**

### CODE REVIEW

**Comment by marliekeverweij** [comment]
@antw would you have time to look into the failure?

We have made the HHP input efficiencies dynamic, because we had problems with the fixed input efficiencies for `nl2019`

We see that the failure has to do with: 
```
- output.useable_heat.ambient_heat = 1.0
- output.useable_heat.electricity = 1.0
- output.useable_heat.network_gas = 1.07
```

When we change  `output.useable_heat = 1.0` it works

**Comment by antw** [comment]
```
- output.useable_heat.ambient_heat = 1.0
- output.useable_heat.electricity = 1.0
- output.useable_heat.network_gas = 1.07

~ input.electricity = EFFICIENCY(households_space_heater_hybrid_heatpump_air_water_electricity, input, electricity)
~ input.network_gas = EFFICIENCY(households_space_heater_hybrid_heatpump_air_water_electricity, input, network_gas)
~ input.ambient_heat = EFFICIENCY(households_space_heater_hybrid_heatpump_air_water_electricity, input, ambient_heat)
```

Sorry to say that what you're doing here isn't currently supported. The output efficiency of useable heat is "carrier-efficient". That is... its value is determined by the share of the inputs. **It is not supported for those inputs to be defined by a query**, because the share of the output is calculated before queries are run.

I imagine that this limitation could be overcome: I will investigate how we might achieve this, but I'm doubtful that it will be possible before tomorrow.

**Comment by marliekeverweij** [comment]
Okay, too bad! This was the easiest way for us to be able to fix this HHP issue for the `nl2019`and we do not see another route yet.

> I imagine that this limitation could be overcome: I will investigate how we might achieve this, but I'm doubtful that it will be possible before tomorrow.

Would be great if this limitation could be overcome. It would be best if this is done before tomorrow, but not necessary: we can change our planning! How long do you think you will need to fix this?

**Comment by antw** [comment]
I have this done locally, but it does not seem to have the desired effect. It's still tripping up with validation errors:

```
Post-calculation validations failed with the following errors:

  * #<Refinery::Slot (in, network_gas) node=:households_space_heater_hybrid_heatpump_air_water_electricity> demand (61.074979 PJ) does not match demand from the node (61.085685 PJ) (-10,705,384.771482 MJ)
  * #<Refinery::Slot (in, network_gas) node=:households_water_heater_hybrid_heatpump_air_water_electricity> demand (13.919102 PJ) does not match demand from the node (13.921542 PJ) (-2,439,777.188483 MJ)
```

Was this expected?

**Comment by marliekeverweij** [comment]
No, this wasn't expected. Maybe my last commit made things worse... Is it possible to check it without that commit?

**Comment by antw** [comment]
To clarify: The node has slightly less input network gas than is expected. The electricity and ambient heat exactly match what is expected.

Space heater HHP demand: `453.2085747834431`

| Thing | `slot.demand / slot.share` |
| :-- | --: |
| Ambient heat | `453.20857478344310` |
| Electricity | `453.20857478344310` |
| Network gas | `453.20832970287086` |

> Maybe my last commit made things worse... Is it possible to check it without that commit?

It's much better with the latest commit. It's off by thousands of MJ instead of millions.

### Latest commit "Export NL2019 with updated residences_analysis on ETDataset":

```
Post-calculation validations failed with the following errors:

  * #<Refinery::Slot (in, network_gas) node=:households_space_heater_hybrid_heatpump_air_water_electricity> demand (71.956866 PJ) does not match demand from the node (71.956905 PJ) (-38,911.972305 MJ)
  * #<Refinery::Slot (in, network_gas) node=:households_water_heater_hybrid_heatpump_air_water_electricity> demand (17.117489 PJ) does not match demand from the node (17.117498 PJ) (-9,256.590681 MJ)
```

### Previous commit "Add HHP input efficiencies to all country datasets":

```
Post-calculation validations failed with the following errors:

  * #<Refinery::Slot (in, network_gas) node=:households_space_heater_hybrid_heatpump_air_water_electricity> demand (61.074979 PJ) does not match demand from the node (61.085685 PJ) (-10,705,384.771482 MJ)
  * #<Refinery::Slot (in, network_gas) node=:households_water_heater_hybrid_heatpump_air_water_electricity> demand (13.919102 PJ) does not match demand from the node (13.921542 PJ) (-2,439,777.188483 MJ)
```

**Comment by antw** [comment]
Here's the debugging output from Refinery for that node and its edges:

```
|  827 | :households_final_demand_for_space_heating_network_gas -:network_gas-> :households_space_heater_hybrid_heatpump_air_water_electricity                                            | EdgeDemand::ByShare (parent_share)      |     61.07497946 |
|  922 | :households_final_demand_for_space_heating_electricity -:electricity-> :households_space_heater_hybrid_heatpump_air_water_electricity                                            | EdgeDemand::ByShare (parent_share)      |      58.8458764 |
|  926 | [:households_space_heater_hybrid_heatpump_air_water_electricity]                                                                                                                 | NodeDemand::FromCompleteEdge            |     443.5838815 |
| 1041 | :environment_air_ambient_heat -:ambient_heat-> :households_space_heater_hybrid_heatpump_air_water_electricity                                                                    | EdgeDemand::ByShare (child_share)       |     323.6523202 |
| 1293 | :households_space_heater_hybrid_heatpump_air_water_electricity -:useable_heat-> :households_space_heater_hybrid_heatpump_air_water_electricity_aggregator                        | EdgeDemand::ByShare (parent_share)      |     447.8598794 |
```

That's probably not very easy to understand. The calculation process for this node is:

1. (827) Calculate the amount of network gas in the gas edge. This is determined by taking the demand of the **parent** node ("households_final_demand_for_space_heating_network_gas") and multiplying by the edge's parent share.
2. (922) Calculate the amount of electricity in the electricity edge. As with gas, enough data is available on the parent ("households_final_demand_for_space_heating_electricity") to do this.
3. (926) Calculate the demand of the HHP node, using the demand of the electricity edge (edge demand ÷ child share ÷ share of electricity input).
4. (1041) Calculate the amount of ambient heat input, using the HHP demand.
5. (1293) Calculate the amount of useable heat leaving the HHP.

I think the conclusion is that either the electricity amount is slightly too high, or the gas amount is slightly too low.

Could it be that the shares of the [electricity](https://github.com/quintel/etsource/blob/6604fd8a779e07f2ade7a6a3d0afa6338c93390b/graphs/energy/edges/households/households_final_demand_for_space_heating_electricity-households_space_heater_hybrid_heatpump_air_water_electricity%40electricity.ad) or [gas](https://github.com/quintel/etsource/blob/6604fd8a779e07f2ade7a6a3d0afa6338c93390b/graphs/energy/edges/households/households_final_demand_for_space_heating_network_gas-households_space_heater_hybrid_heatpump_air_water_electricity%40network_gas.ad) edges are slightly off?

**Comment by marliekeverweij** [comment]
Thanks for allowing the dynamic input shares! And for you error analysis.

> Could it be that the parent shares of the electricity or gas edges are slightly off?

Maybe, but I do not know how that could have happened. Haven't changed those shares

**Review by marliekeverweij — APPROVED** [review]

**Pull request merged**
