### PR TITLE
Added nodes and edges for LNG (ships and trucks).

### PR DESCRIPTION
**Pull request by RobTerwel**
hard-coded share need to get real csv files. Documentation needed.

### CODE REVIEW

**Comment by RobTerwel** [comment]
Including @ChaelKruip

**Comment by RobTerwel** [comment]
Semaphore fails because some converters have been removed, for which shares are set in preset scenarios. Probably requires renaming the shares in all preset scenarios and countries in the database,  assigning myself to find out whether that solves the problem.

**Comment by ChaelKruip** [comment]
> Probably requires renaming the shares in all preset scenarios and countries in the database, assigning myself to find out whether that solves the problem.

:+1:

**Comment by RobTerwel** [comment]
Got it! What I did to solve this locally for one scenario (the dwars_groen_links one) was:

 - Redefine `user_values.transport_ship_using_biodiesel_share` to `user_values.transport_shipping_mixer_diesel_biodiesel_share`
 - Redefine `user_values.transport_ship_using_diesel_share` to `user_values.transport_shipping_mixer_diesel_diesel_share`
 - Redefine `user_values.transport_ship_using_heavy_fuel_oil_share` to `user_values.transport_shipping_mixer_diesel_heavy_fuel_oil_share`

The new shares can be found in the latest commit https://github.com/quintel/etsource/commit/51e4d9993a90140731594055197b1bcf8af604f7  

This should now be done for all preset scenarios, saved scenarios and countries.

@ChaelKruip or @grdw ,  could you maybe help me with this?

**Comment by RobTerwel** [comment]
Check passed! The database with user saved scenarios should still be updated though.

**Comment by jorisberkhout** [comment]
Excellent work, @RobTerwel ! Merging.

**Pull request merged**
