### PR TITLE
New input statements for Ameland

### PR DESCRIPTION
**Pull request by dennisschoenmakers**
@AlexanderWirtz can we merge this into master and deploy to staging? So we can put the Ameland scenario On The Line :smile:

### CODE REVIEW

**Comment by dennisschoenmakers** [comment]
Scenario is already present on staging server: id #458633

**Comment by dennisschoenmakers** [comment]
open it here: http://beta.pro.et-model.com/scenarios/458633

**Comment by AlexanderWirtz** [comment]
Note that this scenario is not nearly finished. I just got started with space heating and hot water. 

All other sectors still TBD. First, I wanted to see if this would work before creating the other 50 or so I put statements required. 

Creating a scenario this way is quite laborious the first time.

**Comment by AlexanderWirtz** [comment]
Merged

**Pull request merged**
